version: "3.9"

services:
  frontend:
    build:
      context: ..           # ← projektový root, NE backend!
      dockerfile: frontend/Dockerfile
    ports:
      - "10001:80"
    restart: unless-stopped
    networks:
      - portfolio

  backend:
    build:
      context: ..           # ← projektový root, NE backend!
      dockerfile: backend/Dockerfile

    ports:
      - "10000:80"
    volumes:
      - ../backend/content-resources:/app/data
    environment:
      DATA_PATH: /app/data/
    restart: unless-stopped
    networks:
      - portfolio

  proxy:
    image: nginx:alpine
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
    depends_on:
      - frontend
      - backend
    volumes:
      - ./portfolio/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./portfolio/html:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - portfolio

networks:
  portfolio: