services:
  frontend:
    image: jardathedev/personal-portfolio-frontend:latest
    restart: unless-stopped
    pull_policy: always
    networks:
      - portfolio

  backend:
    image: jardathedev/personal-portfolio-backend:latest
    restart: unless-stopped
    pull_policy: always
    networks:
      - portfolio

  web:
    image: nginx:alpine
    container_name: portfolio-nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    volumes:
      - ./portfolio/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - tunnel-portfolio
      - portfolio

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      - web
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_PORTFOLIO_TOKEN}
    networks:
      - tunnel-portfolio

networks:
  tunnel-portfolio:
  portfolio:
