version: "3.9"

services:
  frontend:
    image: docker.io/jardathedev/personal-portfolio-frontend:latest
    restart: unless-stopped
    pull_policy: always
    networks:
      - portfolio

  backend:
    image: docker.io/jardathedev/personal-portfolio-backend:latest
    restart: unless-stopped
    pull_policy: always
    volumes:
      - ./content-resources:/app/data
    environment:
      DATA_PATH: /app/data/
    networks:
      - portfolio

  proxy:
    image: nginx:alpine
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
    depends_on:
      - frontend
      - backend
    volumes:
      - ./portfolio/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./portfolio/html:/usr/share/nginx/html:ro
    networks:
      - tunnel-portfolio
      - portfolio

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      - proxy
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_PORTFOLIO_TOKEN}
    networks:
      - tunnel-portfolio

networks:
  tunnel-portfolio:
  portfolio: